


**PRINCIPALES RÉALISATIONS 2024**

## MOBITIC

Bilan 2024 : Le SSP Lab a travaillé à l’étude d’indicateurs de population présente et de mobilité à partir des nouvelles données disponibles sur la zone. Un stagiaire en troisième année de l’ENSAE a étudié la ségrégation socio-spatiale au sein de l’agglomération lyonnaise. Le SED de Lyon et le SSP Lab ont co-écrit un Insee Analyse, publié en novembre 2024, décrivant les caractéristiques socio-démographiques du territoire d’étude à partir des données Insee. Un encadré y décrit la population présente en journée observée dans les données de téléphonie mobile. Des travaux conjoints 



## ESSNet MNO MINDS

Contexte : le SSP Lab participe à l’ESSnet “Trusted Smart Statistics: methodological developments based on new data sources”. Cet ESSnet, financé par Eurostat de décembre 2023 à décembre 2025, regroupe dix pays européens et est coordonné par l’Italie. L’objectif est de développer un cadre méthodologique commun permettant de combiner données de téléphonie mobile et autres sources de données. Les données considérées appartiennent à deux grandes catégories : les données “statistiques” collectées par les INS dans le but premier d’effectuer des statistiques (recensement, enquêtes) ; les données “non statistiques” collectées en premier pour d’autres usages et ensuite réutilisées pour la statistique (données administratives, capteurs de trafic routier, données de billettique de transport en commun,...). Le SSP Lab a coordonné de décembre 2023 à janvier 2024 le premier groupe de travail de l’ESSnet, qui a pour but de dresser un panorama des sources de données à combiner aux données mobiles en analysant leurs avantages et limites. Eurostat souhaite notamment que ce panorama prenne en compte l’arbitrage entre la qualité des données et leur coût (d’acquisition ou de traitement suivant la source). L’objectif est de se placer dans une perspective de production régulière de statistiques officielles et plus seulement de statistiques expérimentales. De plus, il s’agit de considérer la disponibilité potentielle dans tous les pays européens.
Le deuxième groupe de travail de cet ESSnet a pour but de développer des méthodes et outils permettant de combiner données mobiles et autres sources de données. Ces outils seront open-source et donc mis à disposition de tous les INS. Ils considéreront différents niveaux d’agrégation des données utilisées (données individuelles, données agrégées, combinaison des deux,…)

Enfin, le troisième groupe travaille sur la preuve du concept d’une enquête ad-hoc permettant de mieux comprendre les usages des téléphones et ainsi de mieux analyser les données de téléphonie mobile.
L’ESSnet se concentre sur les données de téléphonie mobile, mais les réflexions pourront à terme s’étendre à d’autres nouvelles sources de données. 


Les pays partenaires qui accèdent à des données les reçoivent dans le cadre de partenariats avec des opérateurs, avec un niveau d’agrégation similaire à ce à quoi l’Insee accède dans le cadre de MOBITIC. Les cas d'application qui ont retenu l’intérêt des partenaires rejoignent grandement ceux que MOBITIC prévoit d’étudier. Les fortes adhérences entre ces deux projets permettent donc d’espérer des mutualisations fructueuses. 

Bilan 2024 : en tant que coordinateur du groupe de travail consacré au panorama des sources à combiner aux données de téléphonie mobile, le SSP Lab a activement contribué à la préparation du séminaire de deux jours et demi en juin 2024 à Vienne, destiné à élargir les discussions de l’ESS-Net au-delà des instituts de statistique nationale participants au projet. En particulier, des opérateurs de téléphonie mobile de plusieurs pays ont participé, ainsi que des entreprises agrégatrices de données et une entreprise à mission spécialisée dans l’analyse des données mobiles pour les pays en voie de développement (FlowMinder).  De par la diversité des participants, le séminaire a été très enrichissant, et a permis de recueillir des avis et idées sur les forces et faiblesses des données à combiner aux données de téléphonie mobile. Le S2 2024 a été consacré à la valorisation des échanges ayant eu lieu lors du séminaire, et à l’élaboration du deuxième rendu du groupe de travail, livré à Eurostat en août. Ce rendu propose une grille d’analyse des forces et faiblesses des sources de données à combiner aux données de téléphonie mobile, ainsi qu’une analyse détaillée de 16 sources. Deux papiers ont été soumis aux conférences NTTS et ISI et retenus dans le cadre d’une session spéciale dédiée à la téléphonie mobile. 
Programme 2025 : compte-tenu de la mobilité de MP Joubert, l’Allemagne reprend le lead du WorkPackage. Le SSPLab reste toutefois impliqué en tant que contributeur. 

Le SSP-Lab sera impliqué dans l’organisation de la conférence finale de l’ESSNet, qui aura lieu dans les locaux de l’OCDE en septembre prochain.  

Développement, implémentation et démonstration d’un pipeline de référence pour la production de statistiques officielles basé sur les données de multiples opérateurs de téléphonie mobile (projet Multi-MNO)
Contexte : compte tenu du potentiel des données de téléphonie mobile pour produire des statistiques officielles sur la population présente et la mobilité, Eurostat finance un consortium européen qui développe un cadre méthodologique et un logiciel open-source permettant aux INS d’exploiter les données de téléphonie mobile. Le projet est coordonné par un cabinet de conseil (GOPA). Le consortium réunit quatre INS (CBS Pays-Bas, ISTAT Italie, GUS Pologne et SURS Slovénie), deux entreprises spécialisées dans le traitement de données mobiles (Positium et Nommon) et cinq opérateurs de téléphonie mobile, issus de quatre pays différents (Orange Espagne, Vodafone Espagne, Vodafone Italie, A1 Slovénie et POST Luxembourg).
Eurostat souligne l’intérêt que deux opérateurs du même pays participent au projet. Cela permettra ainsi de démontrer d’un point de vue technique et organisationnel, la possibilité de produire des statistiques à partir de données d’opérateurs concurrents au sein d’un même pays. Les opérateurs fourniront l’accès à leurs données pour tester, évaluer et améliorer le circuit de traitement des données développé durant le projet. Seules les données agrégées et anonymisées quitteront les serveurs des opérateurs de téléphonie mobile. L’objectif est que les traitements développés dans le cadre du projet puissent traiter les données individuelles directement sur les serveurs des opérateurs. Certains éléments de la méthode d’agrégation resteront paramétrables, de façon à s’ajuster aux exigences nationales et notamment aux contraintes réglementaires, qui peuvent différer suivant les pays. Une attention particulière sera portée au respect des informations commerciales sensibles pour les opérateurs. Par exemple, les poids utilisés pour garantir la représentativité des statistiques ne seront pas publiés. Des experts du domaine juridique font partie du consortium.

Les cas d’usage principaux sont : population présente, mobilité, étude de la dynamique des aires urbaines fonctionnelles, analyse de la fréquentation touristique, exposition aux risques, migrations internes.   
La proposition a été validée par Eurostat en décembre 2022. Le projet a démarré en janvier 2023 et est prévu pour durer 30 mois, jusqu’à juin 2025.

*Bilan 2024* : le SSP Lab et des représentants d’Orange France font partie du comité de suivi du projet. Ce comité émet des avis sur les définitions, méthodologies, choix des cas d’usage, protection des données. L’objectif de cette participation est, pour le SSP Lab, que les conclusions du projet soient les plus transposables possibles en France.
Trois réunions ont eu lieu en 2024 (janvier, mars et mai). Des échanges nourris ont permis de contribuer à améliorer les rendus du projet. Une première version de ceux-ci a été publiée en décembre 2024. Le premier livrable décrit le cadre méthodologique : architecture générale, pré-requis, cas d’usage et méthodes. Le deuxième livrable décrit le cadre qualité et les modèle économique. Le troisième livrable présente les logiciels open-source utilisés pour construire le pipeline ainsi que la documentation technique. L’ensemble des codes et données tests est accessible sur le repository github du projet.   

*Programme 2025* : le SSPLab continuera sa participation au comité de suivi du projet. Les prochaines réunions aborderont les premiers tests du pipeline sur deux premiers cas d’usage. A terme, six cas d’usage seront traités dans la version finalisée en juin 2025. 













[]{#anchor-6}**PRINCIPALES RÉALISATIONS 2023**



[]{#anchor-7}Mise en production des modèles de codification automatique



L'année 2023 a d'abord été marquée pour le SSP Lab par le premier
passage en production à l'Insee d'un modèle d'apprentissage supervisé
prédisant l'appartenance à une nomenclature et par la préparation du
passage en production de modèles similaires.



L'algorithme permettant de coder l'Activité principale de l'entreprise a
été mis en production en janvier 2023. En juin 2023, les gestionnaires
Sirene ont signalé un problème de classification fréquent pour les
loueurs de meublé non professionnel. Un nouveau modèle a été entraîné et
déployé pour corriger cela.



En 2023, la DMTR et le SSP Lab ont collaboré sur des travaux
méthodologiques liés à la mise en production de l'algorithme fastText
pour coder les libellés de professions déclarées dans l'enquête annuelle
de recensement dans la nouvelle nomenclature de professions et
catégories socioprofessionnelles 2020. En parallèle, à la demande du CD
PTT, le SSP Lab et la DRTI ont travaillé sur la mutualisation des outils
de codification en PCS2020. Au premier semestre 2023, un stagiaire en
césure de l'ENSAE a créé une architecture de code pour la réalisation
des tests de performance liés à la mutualisation de plusieurs bases
d'enquête, notamment issues du TCM (Tronc Commun des enquêtes Ménage).
Au deuxième semestre, les performances de différents modèles ont été
comparées.



Le SSP Lab et la division Indice des prix à la consommation ont
co-encadré un stage consacré au développement d'un algorithme
d'apprentissage supervisé permettant de coder les produits de Lidl dans
la COICOP^13^. Le SSP Lab a également travaillé avec la division
Condition de Vie des Ménages pour explorer les limites de l'utilisation
du modèle de prédiction utilisé sur les données de caisse pour classer
les libellés des produits de l'enquête Budget de famille dans la
nomenclature COICOP.



Les trois premières sessions du groupe de veille sur la codification
automatique lancé en 2023 ont permis de partager les connaissances
internes sur le sujet, les différentes expériences et ressources des uns
et des autres. Durant les deux suivantes, les participants ont reçu une
formation au MLOps centrée sur les bonnes pratiques de développement
d'applications de codification, prévu pour plusieurs équipes en 2024.





[]{#anchor-8}Préparation et lancement de plusieurs projets avec des
partenaires extérieurs



Le deuxième axe d'investissement majeur pour le SSP Lab en 2023 a été la
préfiguration et le lancement de plusieurs projets de collaboration avec
des organismes extérieurs, issus du milieu académique ou privé, en
France et à l'international.



Le SSP Lab et la DIIT se sont fortement impliqués dans la préparation de
la réponse à l'appel à projet d'Eurostat destiné à créer un centre de
ressources européen en intelligence artificielle et machine learning
pour les statistiques officielles. Notamment, le SSP Cloud a été choisi
comme plateforme de prototypage des cas d'usage, le SSP Lab est
positionné comme fort contributeur aux ressources de formations et
participera au cas d'usage sur la codification automatique. Le DMS
(DMRG) sera également impliqué sur le cas d'usage sur les données
synthétiques.

Le SSP Lab a également contribué à la préparation de l'ESS Net "*Trusted
Smart Statistics: methodological developments based on new data
sources*" et co-écrit avec les autres participants à la Task Force
lancée par Eurostat sur l'usage des données de téléphonie mobile pour la
statistique publique, un article (*position paper*), publié en septembre
2023, présentant l'intérêt et les grands principes d'une méthodologie
commune à l'ensemble du système statistique européen, pour traiter les
données de téléphonie mobile^14^.



Le SSP Lab a poursuivi en 2023 sa participation à l'ESS Net Web
Intelligence Network, qui vise à automatiser la collecte d'informations
issues du web. Il a principalement évalué le DataLab développé par le
WIN, en le comparant à Onyxia, mais aussi labellisé des offres d'emploi
en français pour l'évaluation du modèle développé dans le cadre d'OJA.
Une première rencontre en présentiel de l'ESSNet a eu lieu à Vienne en
février 2023.



Sur le plan national, deux projets de collaboration entre l'Insee, des
représentants du milieu académique et des entreprises ont pu finaliser
leur préfiguration et démarrer concrètement en 2023. Il s'agit d'une
part du projet MOBITIC, « Estimation des indicateurs de mobilité et de
présence à l'aide des TIC », financé par l'Agence Nationale de la
Recherche et mené en partenariat avec l'Université Gustave Eiffel et
l'opérateur de téléphonie mobile Orange et d'autre part de la
participation de l'Insee à la Chaire Finance Digitale qui regroupe
Télécom Paris, Paris 2, Cartes Bancaires CB (ou GIE CB), la Banque
postale, la Caisse des dépôts et l'Insee, et hébergée à la Fondation du
Risque (Institut Louis Bachelier).





[]{#anchor-9}Réalisation et lancement de nouvelles expérimentations



Le troisième axe de travail du SSP Lab en 2023 a été le prolongement et
l'étoffement d'expérimentations en cours, ainsi que le lancement de
nouvelles expérimentations.



Un important travail a été mené en collaboration avec la division
Profilage et Traitement des Grandes Unités et la Banque de France, sur
l'extraction d'information de tableaux de comptes sociaux (en
particulier des tableaux des filiales et participations) contenus dans
des images scannées mises à disposition par l'INPI via une API. Sur le
thème de l'extraction d'information, le SSP Lab a également collaboré
avec la division ressource et conditions de vie des ménages pour tester
une méthode d'extraction du contenu des tickets de caisse photographiés
par les enquêtés de l'enquête Budget des Familles.



Le SSP Lab a collaboré avec la division Indice des chiffres d'affaires
sur la détection des anomalies dans le processus de calcul des indices
de chiffre d'affaires (Harmonica).



Une expérimentation sur l'usage des données satellitaires, menée par le
SSP Lab et la DMRG, a été lancée en collaboration avec les directions
interrégionales d'Antilles-Guyane et de la Réunion-Mayotte ainsi que la
division Méthodes et traitements des recensements.



Une première version d'un site interactif de datavisualisation sur les
indices de logement issus des données SeLoger.com a été co-construit
avec la Division Logement et Patrimoine. Cette expérimentation a été
l'opportunité d'approfondir la compréhension de technologies modernes de
traitement et de visualisation de données liées aux écosystèmes
JavaScript (par le biais du *framework Observable*) et *DuckDB*. Outre
la fiabilisation de la méthodologie des indices mise en œuvre par la
Division Logement et Patrimoine, la prochaine étape de ce travail sera
la mise en œuvre d'un cadre de publication du site web de
datavisualisation en lien avec la Division Logement et Patrimoine et le
Département de l'Offre Éditoriale.

En lien avec le Département de la conjoncture, un outil permettant de
suivre l'évolution d'indicateurs macroéconomiques européens lors de la
phase de rédaction des notes de conjoncture a été développé. Cet outil,
auparavant construit avec la technologie *R Shiny*, n'était plus
maintenu et avait un certain nombre de dysfonctionnements. Le changement
de couches techniques, autour des *frameworks Observable *et *DuckDB*, a
permis de créer un site plus réactif, plus simple à maintenir (base de
code limitée, pas besoin de serveurs autres qu'un serveur web...) et
plus ergonomique. Le site web obtenu est disponible sur[
](https://radjerad.pages.lab.sspcloud.fr/inflation_internationale/)[*Gitlab
Pages*](https://radjerad.pages.lab.sspcloud.fr/inflation_internationale/).



Enfin, ces nouveaux outils de datavisualisation ont également été
utilisés lors du challenge de nowcasting organisé par Eurostat et à
l'issue duquel une équipe incluant le SSP Lab, le D2E et le DSCT a
obtenu la 3^e^ place. Un[
](https://inseefrlab.github.io/ESA-Nowcasting-2023/)[*site
web*](https://inseefrlab.github.io/ESA-Nowcasting-2023/) créé avec
Quarto a été déployé pour présenter les différentes performances des
modèles utilisés lors de ce challenge. Ce travail pourra à l'avenir
servir d'illustration aux bonnes pratiques de reproductibilité que le
SSP Lab cherche à promouvoir.



Le SSP Lab a travaillé en appui à la diffusion de données au format
Parquet sur deux projets en 2023 :

-   >  Sur la diffusion des bureaux de votes du REU (Répertoire
    > Électoral Unique) et des adresses des électeurs, le SSP Lab a
    > grandement contribué, en collaboration avec la Dinum, à la
    > création de tables diffusables à partir des fichiers bruts de 2022
    > pour une mise en ligne des bases sur data.gouv au format Parquet
    > au début de l'été 2023.

-   >  Sur les données du RP, le SSP Lab a accompagné la diffusion des
    > données au format Parquet sur data.gouv fin 2023 et a notamment
    > réalisé un guide d'utilisation des données par le biais d'un post
    > de[ ](https://ssphub.netlify.app/post/parquetrp/)[*blog du SSP
    > Hub*](https://ssphub.netlify.app/post/parquetrp/) avec des
    > exemples de requêtes utilisant *DuckDB*. S'en est suivie la
    > promotion de la publication sur différents réseaux jusqu'à la[
    > ](https://ssplab.pages.lab.sspcloud.fr/parquet_insee_contact/#/title-slide)[*présentation
    > de
    > l'expérimentation*](https://ssplab.pages.lab.sspcloud.fr/parquet_insee_contact/#/title-slide)
    > avec le pôle ODL (Offre de Données Locales) en janvier 2024.



En 2023, le SSP Lab a contribué à plusieurs travaux utilisant des
méthodes innovantes de data-science pour apparier des bases de données.
Tout d'abord, le[
](https://www.insee.fr/fr/statistiques/7644535)[*document de
travail*](https://www.insee.fr/fr/statistiques/7644535) "Appariements de
données individuelles : concepts, méthodes, conseils" (Lucas Malherbe) a
été publié en juillet 2023. Il s'accompagne d'un dépôt de code évolutif
contenant des exemples d'appariements ainsi que des ressources
d'autoformation. Ainsi, les éléments mis à disposition pourront évoluer
en cas de développement d'une nouvelle technologie d'appariement jugée
suffisamment robuste et prometteuse. Le SSP Lab et la DRTI ont également
accompagné les équipes RESIL dans la construction du moteur
d'appariement spécifique à RESIL. Par ailleurs, le SSP Lab (Lino
Galiana) a présenté en séminaire joint DEE-SSP Lab et à la conférence
ISI 2023 à Ottawa des travaux sur les appariements flous avec
ElasticSearch menés en collaboration avec le Département des Etudes
Economiques pour enrichir les données du corpus OpenFoodsFacts. Enfin,
le SSP Lab et la Dares ont obtenu la 5ème place au niveau européen au
challenge de déduplication des données Online Job Advertisements (OJA)
organisé par Eurostat. La déduplication est un cas particulier des
méthodes d'appariement, puisqu'il s'agit d'apparier un fichier avec
lui-même. De nombreux enseignements ont été tirés de ce travail.





[]{#anchor-10}Diffusion des méthodes et innovations



Enfin, le dernier axe de travail du SSP Lab en 2023 a consisté en
l'appui à la diffusion des méthodes et innovations dans le domaine de la
data-science grâce à l'animation du réseau SSP Hub, à des formations et
des présentations.



Une première journée du réseau SSP Hub a été organisée en avril 2023,
autour de retours d'expérience sur des projets d'innovation statistique
et d'ateliers collaboratifs. Celle-ci a eu lieu en format hybride et a
réuni 50 personnes sur place. Une série de webinaires sur des sujets
techniques, par exemple les librairies *open source* de mise à
disposition des données Insee, a été organisée pendant l'année. Enfin, 8
masterclass sur les méthodes et outils de la data science ont été
organisées en lien avec l'institut spécialisé de formation
datascientest.



Plusieurs membres du SSP Lab se sont impliqués en 2023 dans le programme
interministériel 10%, en particulier sur les deux sujets suivants :

-   >  Cartiflette : un outil destiné à rassembler les données de l'IGN
    > et les référentiels administratifs de l'INSEE dans un point
    > d'entrée clair et normalisé (catalogue de données et API) pour
    > faciliter l'harmonisation et l'association de données
    > géographiques.

-   >  FormIAble : un outil permettant d'extraire automatiquement le
    > contenu de formulaire CERFA, prêt à l'emploi pour un ensemble de
    > formulaires existant et facilement généralisable à de nouveaux
    > formulaires. L'outil est basé sur le modèle Donut entraîné sur des
    > données générées synthétiquement.



Au niveau international, le SSP Lab a participé activement aux réseaux
d'innovation tels l'UNECE ModernStats Blue Skies Thinking Network, le
workshop du HLG-MOS de l'UNECE et l'UN Data Science Leaders Network.



En parallèle du développement du projet de codification automatique de
l'APE, le SSP Lab et la DIIT ont créé une formation au MLOps (reposant
sur les outils MLflow et FastAPI déployés sur Kubernetes), proposée pour
la première fois aux participants du workshop Machine Learning de
l'UNECE en juin 2023^15^. Cette formation détaille quelques bonnes
pratiques lors du cycle de vie d'un modèle d'apprentissage automatique
en production. Elle a également été donnée dans le cadre de la formation
Big Data à la BCEAO puis dans le cadre du groupe de travail interne sur
la codification automatique (avec l'ajout d'un module sur le monitoring
des modèles en production). La formation figure dans le catalogue du SSP
Cloud, en anglais et en français^16^. Les principes du MLOps ont par
ailleurs été présentés lors du séminaire de développement de la DSI,
ainsi qu'à l'encadrement de la direction régionale des Pays de la Loire.



Par ailleurs, le funathon 2023 a été co-organisé par le SSP Lab, la DIIT
et le Service de la Statistique et de la Prospective du 27 au 28 juin
2023. 130 personnes se sont inscrites à l'événement, 60 Insee et 70
inscrits des SSM, du péri-SSP (DREAL...) ou d'autres organismes
(chambres d'agriculture...). Six sujets ont été proposés autour du
thème "Du champ à l'assiette"^17^. Les niveaux des participants
variaient du débutant à l'expert. Une douzaine d'équipes ont présenté le
résultat de leur travail lors de la restitution de clôture. Les retours
ont été dans l'ensemble très positifs et plusieurs agents ont manifesté
leur volonté de poursuivre sur les sujets après la fin du funathon.



Le SSP Lab a également porté en 2023 le développement et l'inscription
au catalogue de formation d'une formation aux bonnes pratiques avec R et
Git^18^. Plusieurs versions de cette formation ont été développées,
notamment des formations de formateurs (à la DG, en DR et en SSM) et des
formations spécifiques au public des managers^19^.



Le SSP Lab a organisé deux sessions de formation à python en interne à
l'Insee (une initiation et un perfectionnement) ainsi qu'une dizaine de
séances de masterclass pour les datascientists du réseau SSP Hub
(principalement sur des thèmes autour du traitement du langage et des
images). Des enseignements ont également été dispensés en formation
initiale dans les écoles du GENES :

-   >  "[*Python pour la data
    > science*](https://pythonds.linogaliana.fr/)", ENSAE 2e année.

-   >  "[*Mise en production de projets data
    > science*](https://ensae-reproductibilite.github.io/website/)",
    > ENSAE 3e année

-   >  "[*Nouvelles sources de
    > données*](https://inseefrlab.github.io/cours-nouvelles-donnees-site/)",
    > ENSAI Master « Science des données pour la décision publique »

-   >  "Analyse Spatiale", ENSAI Master « Science des données pour la
    > décision publique»



L'utilisation de l'IA et du machine learning à l'Insee ont été présentés
au CEFIL, pour les contrôleurs et attachés promus au choix, à l'ENSAI
pour les attachés stagiaires, au séminaire des administrateurs
stagiaires, au séminaire des pôles Insee Contact, ainsi qu'aux agents de
la direction régionale des Pays de la Loire.



En collaboration avec la DIIT, le SSP Lab a dispensé une formation de 4
jours à Dakar, au siège de la BCEAO, dans le cadre de leur "Stratégie
Big Data"^20^. La formation a abordé la place et les enjeux du Big Data
au sein de l'Insee, le MLOps ainsi que les nouvelles sources de données
qui sont utilisées à l'Insee. Les aspects juridiques et réglementaires
liés au Big Data ont également été discutés. Enfin, une nouvelle
formation sur le traitement des données volumineuses avec R a été
élaborée et a été particulièrement bien accueillie. Elle figure
maintenant dans le catalogue de formation du SSP Cloud et pourra être
utilisée dans le cadre du passage de SAS à R.





1 One-stop-shop for Artificial Intelligence -- Machine learning for
official statistics

2* One-stop-shop for Artificial Intelligence -- Machine learning for
official statistics (SMP-ESS-2023-AI-ML4OS-IBA)*

3 [*https://fasttext.cc/*](https://fasttext.cc/)

4 Voir Note n° 2023_26003_DG75-F610 du 21/11/2023.

5
[*https://inseefrlab.github.io/formation-mlops/slides/fr/*](https://inseefrlab.github.io/formation-mlops/slides/fr/)

6 One-stop-shop for Artificial Intelligence -- Machine learning for
official statistics

7 Notamment celle du Web Intelligence Network, qui consiste à traduire
tous les textes en anglais et à entraîner un unique classifieur en
anglais.

8 Construit à partir du framework Langchain et de la base de données
vectorielle ChromaDB (la librairie Faiss a aussi été testée).

9 Une masterclass dure environ trois heures et se compose de deux
parties : la première permet d'aborder les aspects théoriques d'un
sujet, tandis que la seconde offre une mise en œuvre pratique sur un
exemple, l'objectif étant de dérouler un projet réel de bout en bout.

10
[*https://www.statcan.gc.ca/fr/science-donnees/reseau/apprentissage-automatique*](https://www.statcan.gc.ca/fr/science-donnees/reseau/apprentissage-automatique)

11 Applying Data Science and Modern Methods

12 Tel que scikit-learn, par exemple.

13 voir la note n° 2023_26003_DG75-F610 du 21/11/2023

14 [*http://doi.org/10.2785/880645*](http://doi.org/10.2785/880645)

15
[*https://unece.org/statistics/events/ML2023*](https://unece.org/statistics/events/ML2023)

16
[*https://inseefrlab.github.io/formation-mlops/*](https://inseefrlab.github.io/formation-mlops/)

17
[*https://inseefrlab.github.io/funathon2023/*](https://inseefrlab.github.io/funathon2023/)

18[*https://inseefrlab.github.io/formation-bonnes-pratiques-git-R/*](https://inseefrlab.github.io/formation-bonnes-pratiques-git-R/)

19[*https://inseefrlab.github.io/formation-bonnes-pratiques-git-R/slides/manageurs.html*](https://inseefrlab.github.io/formation-bonnes-pratiques-git-R/slides/manageurs.html)

20[*https://inseefrlab.github.io/formation-bceao/*](https://inseefrlab.github.io/formation-bceao/)
